/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerImp;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.TreeSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.DanhSachMua;
import model.KhachHang;
import model.MatHang;

/**
 *
 * @author Admin88
 */
public class MainFrame extends javax.swing.JFrame implements View {

    /**
     * Creates new form MainFrame
     */
    private List<DanhSachMua> listDS;
    private List<MatHang> listMH;
    private List<KhachHang> listKH;
    private ControllerImp control;
    private int idKH, idMH;
    DefaultTableModel modelKH;
    DefaultTableModel modelMH;
    DefaultTableModel modelKH1;
    DefaultTableModel modelMH1;
    DefaultTableModel modelDS;

    public MainFrame() {
        initComponents();
        control = new ControllerImp();
        listMH = new ArrayList<>();
        listKH = new ArrayList<>();
        listDS = new ArrayList<>();
        modelDS = (DefaultTableModel) tbDS.getModel();
        modelKH = (DefaultTableModel) tbKH.getModel();
        modelMH = (DefaultTableModel) tbMH.getModel();
        modelKH1 = (DefaultTableModel) tbKH1.getModel();
        modelMH1 = (DefaultTableModel) tbMH1.getModel();
        showMH();
        showKH();
        show2table();
        showDS();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMH = new javax.swing.JTable();
        bSub1 = new javax.swing.JButton();
        bX1 = new javax.swing.JButton();
        tTH = new javax.swing.JTextField();
        tGia = new javax.swing.JTextField();
        cbN = new javax.swing.JComboBox<>();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbKH = new javax.swing.JTable();
        bSub2 = new javax.swing.JButton();
        bX2 = new javax.swing.JButton();
        tDC = new javax.swing.JTextField();
        tSDT = new javax.swing.JTextField();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        tTKH = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbKH1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbMH1 = new javax.swing.JTable();
        label7 = new java.awt.Label();
        label8 = new java.awt.Label();
        label9 = new java.awt.Label();
        bSub3 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbDS = new javax.swing.JTable();
        bX3 = new javax.swing.JButton();
        label10 = new java.awt.Label();
        tMaKH = new javax.swing.JTextField();
        tMaH = new javax.swing.JTextField();
        label11 = new java.awt.Label();
        bTim1 = new javax.swing.JButton();
        bTim2 = new javax.swing.JButton();
        tSL = new javax.swing.JTextField();
        bSxMH = new javax.swing.JButton();
        bSxKH = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbMH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã", "Tên Hàng", "Nhom", "Gia"
            }
        ));
        jScrollPane1.setViewportView(tbMH);

        bSub1.setText("Submit");
        bSub1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSub1ActionPerformed(evt);
            }
        });

        bX1.setText("Xoa");

        cbN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tieu Dung", "Dien May", "Gia Dung" }));

        label1.setText("Nhóm Hàng");

        label2.setText("Tên Hàng");

        label3.setText("Gía Bán");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tTH, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbN, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bSub1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bX1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(85, 85, 85))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tGia, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bSub1)
                        .addComponent(tTH, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bX1)
                        .addComponent(cbN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tGia, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(300, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mặt Hàng", jPanel1);

        tbKH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã KH", "Tên KH", "Địa Chỉ", "SDT"
            }
        ));
        jScrollPane2.setViewportView(tbKH);
        if (tbKH.getColumnModel().getColumnCount() > 0) {
            tbKH.getColumnModel().getColumn(2).setHeaderValue("Địa Chỉ");
            tbKH.getColumnModel().getColumn(3).setHeaderValue("SDT");
        }

        bSub2.setText("Submit");
        bSub2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSub2ActionPerformed(evt);
            }
        });

        bX2.setText("Xóa");

        label4.setText("Dia Chi");

        label5.setText("Tên KH");

        label6.setText("SDT");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(68, 68, 68)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tDC, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tTKH, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bSub2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bX2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(85, 85, 85))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tTKH, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tDC, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(bSub2)
                        .addGap(39, 39, 39)
                        .addComponent(bX2)))
                .addGap(58, 58, 58)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Khách Hàng", jPanel2);

        tbKH1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã KH", "Tên KH"
            }
        ));
        jScrollPane3.setViewportView(tbKH1);

        tbMH1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã", "Tên Hàng", "Nhom", "Gia"
            }
        ));
        jScrollPane4.setViewportView(tbMH1);

        label7.setText("Khách Hàng");

        label8.setText("Mat Hàng");

        label9.setText("So Luong");

        bSub3.setText("Thêm");
        bSub3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSub3ActionPerformed(evt);
            }
        });

        tbDS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên KH", "Tên SP", "SL", "Tong Tien"
            }
        ));
        jScrollPane5.setViewportView(tbDS);

        bX3.setText("XÓA");
        bX3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bX3ActionPerformed(evt);
            }
        });

        label10.setText("Mã KH");

        label11.setText("Mã MH");

        bTim1.setText("Tìm");
        bTim1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTim1ActionPerformed(evt);
            }
        });

        bTim2.setText("Tìm");
        bTim2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTim2ActionPerformed(evt);
            }
        });

        bSxMH.setText("SX ten MH");
        bSxMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSxMHActionPerformed(evt);
            }
        });

        bSxKH.setText("SX ten KH");
        bSxKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSxKHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(174, 174, 174))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(tSL, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(341, 341, 341))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bX3, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addComponent(bSub3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bTim1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tMaH, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(bTim2)
                .addGap(56, 56, 56))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(bSxKH, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(193, 193, 193)
                .addComponent(bSxMH, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(label10, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                        .addComponent(label11, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                        .addComponent(tMaKH)
                        .addComponent(bTim1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tMaH))
                    .addComponent(bTim2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tSL, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(label9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(bSub3)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bSxMH, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bSxKH, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(bX3)))
                .addGap(252, 252, 252))
        );

        jTabbedPane1.addTab("Danh Sách Mua Hàng", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bX3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bX3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bX3ActionPerformed

    private void bSub2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSub2ActionPerformed
        try {
            String tenKH = tTKH.getText().trim();
            String diaChi = tDC.getText().trim();
            int sdt = Integer.parseInt(tSDT.getText().trim());
            if (tenKH.length() != 0 && diaChi.length() != 0) {
                KhachHang kh = new KhachHang(idKH, tenKH, diaChi, sdt);
                idKH++;
                listKH.add(kh);
                control.writeFile(listKH, "KH.txt");
                showData(listKH, modelKH);
                showData(listKH, modelKH1);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Thong tin khong duoc bo trong");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "SDT phai là so va khong duoc bo trong");
        }
    }//GEN-LAST:event_bSub2ActionPerformed

    private void bSub1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSub1ActionPerformed
        try {
            String tenMH = tTH.getText().trim();
            String nhom = (String) cbN.getItemAt(cbN.getSelectedIndex());
            double gia = 0;
            try {
                gia = Double.parseDouble(tGia.getText().trim());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Gia phai la so");
            }
            if (tenMH.length() != 0 && gia != 0) {
                MatHang mh = new MatHang(idMH, tenMH, nhom, gia);
                listMH.add(mh);
                control.writeFile(listMH, "MH.txt");
                showData(listMH, modelMH);
                showData(listMH, modelMH1);
                idMH++;
            } else {
                throw new Exception();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Ten Mat hang khong duoc bo trong");
        }

    }//GEN-LAST:event_bSub1ActionPerformed

    private void bTim1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTim1ActionPerformed
        String text = tMaKH.getText().trim();
        List<KhachHang> list1 = new ArrayList<>();
        if (text.length() > 0) {
            list1 = control.searchName(listKH, text);
        } else {
            list1 = listKH;
        }
        showData(list1, modelKH1);
    }//GEN-LAST:event_bTim1ActionPerformed

    private void bTim2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTim2ActionPerformed
        String text = tMaH.getText().trim();
        List<MatHang> list1 = new ArrayList<>();
        if (text.length() > 0) {
            list1 = control.searchName(listMH, text);
        } else {
            list1 = listMH;
        }
        showData(list1, modelMH1);
    }//GEN-LAST:event_bTim2ActionPerformed

    private void bSub3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSub3ActionPerformed
        int indexKH = tbKH1.getSelectedRow();
        int indexMH = tbMH1.getSelectedRow();
        if (indexKH == -1 || indexMH == -1) {
            JOptionPane.showMessageDialog(rootPane, "Hay chon Khach hang va Mat Hang o bang tren !");
        } else {
            int sl = Integer.parseInt(tSL.getText());
            MatHang mh = listMH.get(indexMH);
            KhachHang kh = listKH.get(indexKH);

            if (listDS.size() == 0) {
                listDS.add(new DanhSachMua(mh, sl, kh));
            } else {
                int check = 1;
                for (DanhSachMua ds : listDS) {
                    if (ds.getKhachHang().getMaKH() == kh.getMaKH()) {
                        ds.setItems(mh, sl);
                        check = 0;
                    }
                }

                if (check == 1) {
                    DanhSachMua ds1 = new DanhSachMua(mh, sl, kh);
                    listDS.add(ds1);
                }
            }
            control.writeFile(listDS, "QLBH.txt");

            showDataDs(listDS);
        }


    }//GEN-LAST:event_bSub3ActionPerformed

    private void bSxKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSxKHActionPerformed
        listDS = control.sortName(listDS);
        showDataDs(listDS);
    }//GEN-LAST:event_bSxKHActionPerformed

    public class xxx {

        private String tenMatHang;
        private DanhSachMua ds;
        private MatHang mh;

        public xxx(String tenMatHang, DanhSachMua ds, MatHang mh) {
            this.tenMatHang = tenMatHang;
            this.ds = ds;
            this.mh = mh;

        }

        @Override
        public String toString() {
            return tenMatHang;
        }

    }
    private void bSxMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSxMHActionPerformed

        List<xxx> set = new ArrayList<>();

        for (DanhSachMua ds : listDS) {
            Set<MatHang> setMh = ds.getItems().keySet();
            for (MatHang mh : setMh) {
                set.add(new xxx(mh.getTenHang(), ds, mh));
            }
        }
        set.sort(new Comparator<xxx>() {
            @Override
            public int compare(xxx o1, xxx o2) {
                return o1.tenMatHang.compareToIgnoreCase(o2.tenMatHang);
            }
        });
        modelDS.setRowCount(0);
        for (xxx object : set) {
            modelDS.addRow(new Object[]{
                object.ds.getKhachHang().getHoTen(),
                object.tenMatHang,
                object.ds.getItems().get(object.mh),
                tongTien(object.mh.getMaHang(),
                object.ds.getItems().get(object.mh))});
        }
//        for (String s : set) {
//            for (DanhSachMua ds : listDS) {
//                Set<MatHang> setMh = ds.getItems().keySet();
//                for (MatHang mh : setMh) {
//                    if (mh.getTenHang().equals(s)) {
//                        modelDS.addRow(new Object[]{ds.getKhachHang().getHoTen(), s, ds.getItems().get(mh), tongTien(mh.getMaHang(), ds.getItems().get(mh))});
//                    }
//                }
//            }
//        }
    }//GEN-LAST:event_bSxMHActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bSub1;
    private javax.swing.JButton bSub2;
    private javax.swing.JButton bSub3;
    private javax.swing.JButton bSxKH;
    private javax.swing.JButton bSxMH;
    private javax.swing.JButton bTim1;
    private javax.swing.JButton bTim2;
    private javax.swing.JButton bX1;
    private javax.swing.JButton bX2;
    private javax.swing.JButton bX3;
    private javax.swing.JComboBox<String> cbN;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private javax.swing.JTextField tDC;
    private javax.swing.JTextField tGia;
    private javax.swing.JTextField tMaH;
    private javax.swing.JTextField tMaKH;
    private javax.swing.JTextField tSDT;
    private javax.swing.JTextField tSL;
    private javax.swing.JTextField tTH;
    private javax.swing.JTextField tTKH;
    private javax.swing.JTable tbDS;
    private javax.swing.JTable tbKH;
    private javax.swing.JTable tbKH1;
    private javax.swing.JTable tbMH;
    private javax.swing.JTable tbMH1;
    // End of variables declaration//GEN-END:variables

    @Override
    public <T> void showData(List<T> list, DefaultTableModel model) {
        model.setRowCount(0);
        for (T t : list) {
            if (t instanceof MatHang) {
                model.addRow(new Object[]{((MatHang) t).getMaHang(), ((MatHang) t).getTenHang(), ((MatHang) t).getNhomHang(), ((MatHang) t).getGiaBan()});
            } else if (t instanceof KhachHang) {
                model.addRow(new Object[]{((KhachHang) t).getMaKH(), ((KhachHang) t).getHoTen(), ((KhachHang) t).getDiaChi(), ((KhachHang) t).getSDT()});
            }
        }
    }

    private void showMH() {
        listMH = control.readFile("MH.txt");
        if (listMH.size() > 0) {
            idMH = listMH.get(listMH.size() - 1).getMaHang() + 1;

        } else {
            idMH = 1000;
        }

        showData(listMH, modelMH);
    }

    private void showKH() {
        listKH = control.readFile("KH.txt");
        if (listKH.size() > 0) {
            idKH = listKH.get(listKH.size() - 1).getMaKH() + 1;
        } else {
            idKH = 1000;
        }
        showData(listKH, modelKH);
    }

    private void show2table() {
        showData(listKH, modelKH1);
        showData(listMH, modelMH1);
    }

    private void showDataDs(List<DanhSachMua> listDS) {
        modelDS.setRowCount(0);
        for (DanhSachMua ds : listDS) {
            Set<MatHang> set = ds.getItems().keySet();
            for (MatHang mh : set) {
                modelDS.addRow(new Object[]{ds.getKhachHang().getHoTen(), mh.getTenHang(), ds.getItems().get(mh), tongTien(mh.getMaHang(), ds.getItems().get(mh))});
            }
        }
    }

    private double tongTien(int maHang, Integer get) {
        double gia = 0;
        for (MatHang mh : listMH) {
            if (mh.getMaHang() == maHang) {
                gia = (double) mh.getGiaBan();
            }
        }
        return gia * get;
    }

    private void showDS() {
        listDS = control.readFile("QLBH.txt");
        for (DanhSachMua ds : listDS) {
            Set<MatHang> set = ds.getItems().keySet();
            for (MatHang mh : set) {
                System.out.println(mh.getMaHang() + " " + ds.getItems().get(mh));
            }
        }
        showDataDs(listDS);

    }

}
